### ISSUE TITLE
Additional Columns

### ISSUE THREAD

**Issue by Neckross** [kevinblumenfeld/Posh365Demo#2]
Column for LicenseSuite
Column for EnableArchive
Column for ConvertToShared

**Comment by kevinblumenfeld** [comment]
This needs to be added to Posh365 Repo.  This is the Posh365Demo repository

**Comment by kevinblumenfeld** [comment]
I will add soon.. thank you for feedback.  I will also update the matching functions in Posh365

**Comment by kevinblumenfeld** [comment]
This is complete
